Buildings
interactivevislab/GeoTempPlugins pull request #15
Opened 2020-04-02 18:13 UTC by kir1251

2020-04-03 15:59 UTC, Xanadar89 requested changes

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +USTRUCT(BlueprintType)
Какой смысл делать структуру USTRUCT у которой нет ни одной UPROPERTY?

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +USTRUCT(BlueprintType)
к FBuilding тот же вопрос

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
>  	std::vector<FBuildingPart*> Parts;
Надо заменить на TArray

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
>  };
Надо добавить пустую строку в конец файла

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempOSM/Private/OSMLoader.cpp
> +			Parts.Add(*part);
part создается через new и с этим появляется сразу куча проблем
во первых создавать ustruct через new всё же не рекомендуется, а если сильно надо, то как написано в документации:
UStructs, as mentioned earlier, are meant to be a lightweight version of a UObject. As such, UStructs cannot be garbage collected. If you must use dynamic instances of UStructs, you may want to use smart pointers instead, which we will go over later. 
If you create dynamic instances of them, you must manage their lifecycle yourself.
как видно из кода part потом добавляется в wayParts и живет там до скончания веков вызов delete для него не предусмотрен
плюс Parts.Add(*part); добавляет копию part в Parts

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempOSM/Private/OSMLoader.cpp
> +				Buildings.Add(*building);
Тоже самое в массив добавляется копия не правильно созданного FBuilding
part->Owner = building; - указатель сохраняется, но удален он никогда не будет

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +	}
Какой смысл создавать RootComponent здесь?
Он создается один раз и не меняется со временем
Смело можно перенести в конструктор

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +	}
Зачем копировать массивы? Если всё и так хранится в Building, который теперь USTRUCT (хотя поля конечно и не видны, но это пока)

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +		if (part)
а почему проверка здесь, а не выше?

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +			if (part)
вот опять, если part равен nullptr, то всё упадет парой строк выше

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +void ABuildingActor::ReInitialize() { Initialize(this->Building); }
открывающая скобка должна быть с новой строки
и добавь пустую строку

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(FBuildingPart* part, TMap<FString, FString> tags/*, UBuildingsLoaderBase2* owner*/) {
Опять inline в cpp файле
Note: It’s imperative that the function’s definition (the part between the {...}) be placed in a header file, unless the function is used only in a single .cpp file. In particular, if you put the inline function’s definition into a .cpp file and you call it from some other .cpp file, you’ll get an “unresolved external” error from the linker
Если эта функция не вызывается сотни раз в этом cpp файле и сделав её inline действительно что-то улучшит, то лучше inline не писать

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(FBuildingPart* part, TMap<FString, FString> tags/*, UBuildingsLoaderBase2* owner*/) {
плюс правило наименования входных переменных не соблюдается

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +void UBuildingPartComponent::CreateSimpleStructure(float zeroH)
правило наименования входных переменных не соблюдается

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +void UBuildingPartComponent::SetHeightAlpha(float HeightAlpha)
правило наименования входных переменных не соблюдается

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +void UBuildingPartComponent::ApplyCurrentTime(FDateTime CurrentTime, bool MustHide)
правило наименования входных переменных не соблюдается

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +	float buildDuration = FMath::Max((BuildingDates.BuildEnd - BuildingDates.BuildStart).GetTotalDays(), 1.0);
здесь можно выровнять

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingSpawner.cpp
> +		if (dynamic_cast<ABuildingActor*>(child))
лучше всё же использовать анриловский Cast

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingSpawner.cpp
> +			toDestroy.Add(dynamic_cast<ABuildingActor*>(child));
не надо кастить второй раз, лучше перед if завести переменную

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +#pragma warning( disable : 4456 )
это надо убрать, а к варнингу прислушаться

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +		buildingPart->MinHeight	= buildingPart->MinFloors	* 350.0f - 50;
magic numbers

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +	VertexColors.	Empty();
точки к Empty надо сдвинуть

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +		VertexColors.	Add(FLinearColor::Gray		);
точки вправо

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +void MeshHelpers::ConstructRuntimeMesh(URuntimeMeshComponent* runtimeMesh, FBuildingMeshData meshData)
имена не соответствуют стилю

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/ModernFlatRoof.cpp
> +FBuildingMeshData UModernFlatRoofMaker::GenerateRoof_Implementation(FBuildingPart buildingPart, int firstSectionIndex,
имена не соответствуют стилю

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/ModernFlatRoof.cpp
> +	int z = Vertices.Num();
надо переименовать во что то более говорящее

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/SkeletonSlopeRoof.cpp
> +FBuildingMeshData USlopeRoofMaker::GenerateRoof_Implementation(FBuildingPart buildingPart, int firstSectionIndex, UMaterialInterface* wallMaterial,
имена не соответствуют стилю

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/SkeletonSlopeRoof.cpp
> +	std::vector<int> triangles;
используй TArray

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/SkeletonSlopeRoof.cpp
> +			cont.Points.RemoveAt(0);
если есть выбор удалить первый элемент массива или последний, то удалять надо последний, мало ли какая там реализация

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +	URuntimeMeshComponent* mesh;
Надо с большой буквы

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +	FBuildingPart* partData;
должно быть с большой буквы и в верхнем блоке

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +	void Init(FBuildingPart* part, TMap<FString, FString> tags/*,UBuildingsLoaderBase2 * owner = nullptr*/);
имена не соответствуют стилю

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +	static void SetLodDistance(float dist = 250000) { SimplifyDistance = dist; }
имя не соответствуют стилю

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +	void SetHeightAlpha(float HeightAlpha);
имя не соответствуют стилю, в общем я дальше писать об этом не буду, ты пробегись по всем функциям и переименуй что надо

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingPart.h
> +};
пустую строку в конец файла

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingUtils.h
> +	}
все реализации функций должны быть в cpp файле, если они не inline (в анриле для инлайна используется FORCEINLINE, если я правильно помню)

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingUtils.h
> +	}
та же проблема

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/BuildingUtils.h
> +};
пустую строку

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/RoofMakers/ModernFlatRoof.h
> +};
строку

2020-04-03 15:59 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/RoofMakers/SkeletonSlopeRoof.h
> +};
строку

2020-04-03 16:13 UTC, kir1251 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +USTRUCT(BlueprintType)
Чтобы можно было использовать в TArray и не плодить std::vector'ы. И чтобы передавать их по надобности между блюпринтами, пусть даже не видя, что там внутри.

2020-04-03 16:16 UTC, kir1251 commented on GeoTempCore/Source/GeoTempOSM/Private/OSMLoader.cpp
> +			Parts.Add(*part);
Так, с какого перепуга добавление указателя добавляет копию?

2020-04-03 16:56 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempOSM/Private/OSMLoader.cpp
> +			Parts.Add(*part);
Parts.Add(*part); - вот тут ты указатель добавляешь хочешь сказать?

2020-04-03 17:11 UTC, kir1251 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +	}
Чтобы если какие-то изменения и чистки делались внутри здания, это не повредило Building, который может использоваться где-то ещё, или в свете последних событий писаться назад в базу.

2020-04-03 17:36 UTC, kir1251 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +USTRUCT(BlueprintType)
Короче, все правки по Core переносим в следующий пул-реквест

2020-04-03 17:37 UTC, kir1251 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +USTRUCT(BlueprintType)
И там ещё раз проверяем. Потому что многое я пофиксил, а другое требует уточнения архитектурно.

2020-04-03 17:38 UTC, kir1251 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +	}
Когда-то давно это было написано так, потому что иначе не работало. Я проверю, можно ли безнаказанно перенести это в конструктор, когда вмёржим файл в ветку с загрузчиком OSM с API

2020-04-06 08:34 UTC, Xanadar89 approved these changes

2020-04-06 08:34 UTC, merged