Buildings osm
interactivevislab/GeoTempPlugins pull request #16
Opened 2020-04-02 18:17 UTC by kir1251

2020-04-06 12:35 UTC, Xanadar89 requested changes

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +TArray<FBuilding> UOSMBuildingLoader::GetBuildings(UOsmReader* source)
имя source не соответствует стилю, для остальных функций такой комментарий оставлять не буду

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	TArray<FBuildingPart> Parts;
почему с большой буквы?

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	std::unordered_map<long, FBuildingPart*> buildingWayParts;
надо заменить на TMap

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			std::vector<FVector> points;
заменить на TArray и сразу зарезервировать нужное количество памяти

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +				auto c = new FContour();
плохое имя для переменной

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +					currentPart->OuterConts.Add(*c);
вот здесь записывается копия того что хранится по адресу c, вот только сама c нигде после этого не удаляется, так что здесь у нас утечка памяти

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +				auto c = new FContour();
еще раз на всякий случай delete для с нигде не вызывается, утечка памяти

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			buildings.Add(*building);
здесь также записывается копия building, а сам building остается в памяти мусором

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			building->MainPart = part;
здесь сохраняется указатель на part, ок part мы не теряем, но при удалении всех зданий нигде не будет вызван delete для MainPart (в деструкторе это делать нельзя, либо пользоваться умными указателями), так что либо переходим на умные указатели, либо храним копию part, а сам part в конце удаляем

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			part = new FBuildingPart(relation->Id);
те же самые проблемы с part и с 'c'

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +				auto& currentPart = part;
зачем это вообще надо? только в заблуждение вводит, да еще и имя длиннее получается
и далее также

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			buildings.Add(*building);
хотя это не совсем так, в комментарии выше на 81 строчке объясняется что происходит

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +			part->Owner = building;
а вот это вообще интересно, part хранит ссылку на owner (building[0]) который был создан с помощью new, когда building[0] добавляется в массив, то добавляется его копия, так что получается что в массиве есть building[1] который хранит ссылку на part, который хранит ссылку (owner) на другой building[0]
это может привести к весьма неприятным багам в зависимости от того через что ты хочешь менять building

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +inline const FString* FindBuildingTag(TMap<FString, FString> inTags, FString inTag, FString inTagPrefix = "building:")
опять inline

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	auto floorsTag = FindBuildingTag(inWay->Tags, "levels");
волшебные имена, возможно стоит вынести в константы как минимум

2020-04-06 12:35 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Public/OSM/OSMBuildingLoader.h
> +class UOSMBuildingLoader : public UActorComponent
ээээ, говорят это уже поправили

2020-04-06 13:26 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	TArray<FBuildingPart> Parts;
Если ты про OSM, то это уже поправлено в той ветке, в которой я работаю сейчас.

2020-04-06 13:31 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	std::unordered_map<long, FBuildingPart*> buildingWayParts;
Эти штуки вообще не нужны, странно, что я их не дочистил (они были нужны для поиска потерявшихся Building:Part, которые не имели ссылку на само здание, но это всё равно не работало и было выпилено)

2020-04-06 13:33 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +				auto& currentPart = part;
Остался мусорный код (она ещё и нигде не использовалась)

2020-04-06 13:35 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +					currentPart->OuterConts.Add(*c);
Да, ты уже выше про это написал. Это всё последствия того, что раньше в этих массивах были указатели, и я не слишком внимательно чистил код после этого.

2020-04-06 13:37 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	TArray<FBuildingPart> Parts;
я не знаю почему эта фигня показывает несколько строк, но жалоба была на Parts

2020-04-06 13:41 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +inline const FString* FindBuildingTag(TMap<FString, FString> inTags, FString inTag, FString inTagPrefix = "building:")
Ну вообще тут он как раз по делу — это локальная функция, использующаяся только из этого файла

2020-04-06 13:42 UTC, kir1251 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +	auto floorsTag = FindBuildingTag(inWay->Tags, "levels");
Согласен, сейчас стоит вынести, но вообще тут надо дорабатывать систему с тегами.

2020-04-07 15:43 UTC, Xanadar89 requested changes

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Private/Basics.cpp
>  	TArray<int>& outTriangles, std::string inFlags, TArray<FContour> inOtherLines, int& outContourPointsNum)
почему массив TArray<FContour> inOtherLines не по ссылке
std::string inFlags надо избавиться от std::string и преобразовать ее в нужный тип внутри перед вызовом триангулятора

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Private/Contour.cpp
> +
две пустые строки между функциями

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
> +
две строки

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/OSMBuildingLoader.cpp
>  	TArray<FBuildingPart> Parts;
почему Parts с большой буквы, второй раз спрашиваю

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Public/OSM/OSMBuildingLoader.h
> +class UOsmBuildingLoader : public UActorComponent
Почему компонент?

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +void ABuildingActor::Initialize(FBuilding inBuilding, bool inInitPartsImmideately)
inBuilding лучше по ссылке передавать, да и вообще во всех функциях лучше по ссылке передавать

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(const FBuildingPart& inPart, TMap<FString, FString> inTags/*, UBuildingsLoaderBase2* owner*/) {
и тут TMap не по ссылке

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(const FBuildingPart& inPart, TMap<FString, FString> inTags/*, UBuildingsLoaderBase2* owner*/) {
и inline этот чёртов

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
>  	}
зачем копировать по одному элементу? два массива одинакового типа

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(const FBuildingPart& inPart, TMap<FString, FString> inTags/*, UBuildingsLoaderBase2* owner*/) {
а Init может быть вызван дважды? сейчас этому ничего не мешает и контуры будут копиться

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +	//}
и зачем нам этот мусор

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/ModernFlatRoof.cpp
>  	TArray<FLinearColor>	VertexColors;
VertexColors с большой буквы зачем то

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/ModernFlatRoof.cpp
> +			int iPrev = (i + cont.Points.Num() - 1)	% cont.Points.Num();
cont.Points.Num() лучше вынести за цикл в переменную

2020-04-07 15:43 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/SkeletonSlopeRoof.cpp
> +		auto cont1 = cont;
cont1 плохое название, скорее уж contCopy

2020-04-07 16:54 UTC, kir1251 commented on GeoTempVis/Source/GeoTempBuildings/Private/RoofMakers/ModernFlatRoof.cpp
>  	TArray<FLinearColor>	VertexColors;
Смутили только они, или всё же все переменные меша?

2020-04-07 16:57 UTC, kir1251 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingActor.cpp
> +void ABuildingActor::Initialize(FBuilding inBuilding, bool inInitPartsImmideately)
Хрен знает, как это упустил, проходился везде поиском и заменял на ссылки

2020-04-07 17:00 UTC, kir1251 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingPart.cpp
> +inline void UBuildingPartComponent::Init(const FBuildingPart& inPart, TMap<FString, FString> inTags/*, UBuildingsLoaderBase2* owner*/) {
По хорошему не должен, но я добавил чистку контуров на всякий.

2020-04-07 17:34 UTC, Xanadar89 approved these changes

2020-04-07 17:34 UTC, merged