Map data loader foliage
interactivevislab/GeoTempPlugins pull request #24
Opened 2020-04-10 18:42 UTC by fyodorovvictor

2020-04-13 15:31 UTC, Xanadar89 requested changes

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +inline void FixFoliageContours(FContourData& polygon)
inline функции в cpp файлах будем делать только после того как профилировщик скажет что тут узкое место
так что здесь и далее все функции в cpp файлах делаем не inline

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
пробегаясь по relations ты случаем не трогаешь те же самые ways которые ты пробегал до этого на 31 строчке?

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +					polygon.Holes.Add(contour);
здесь дырки чиним, а потом еще раз на 118 строчке, не слишком ли много фиксов?

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +	for (FFoliageMeshInfo Info : FoliageMeshes)
надо добавить & к FFoliageMeshInfo, сейчас у тебя происходит лишнее копирование

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +			FQuat rotation = FQuat::MakeFromEuler(FVector(0.0f, 0.0f, 0));
Я в прошлый раз писал об этом, почему ничего не поменялось?
что за FQuat::MakeFromEuler(FVector(0.0f, 0.0f, 0))?
почему нельзя было сразу использовать FQuat::Identity

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +					FVector(5.0f)
что за константа?

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +		cellX += CellSize.X; cellY = 0;
почему на одной строке?

2020-04-13 15:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Public/CustomFoliageInstancer.h
> +	void ParseTimeTags(FContourData inContour, TSet<int>& outDates);
здесь можно по константной ссылке inContour передавать

2020-04-14 13:06 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
Не должен. Relation содержит в себе свой набор ways. Логика аналогична той, что сделана в зданиях.

2020-04-14 13:55 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
Relation не содержит в себе другой набор ways, всё что отличается так это тэги

2020-04-14 14:01 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
Мне нужно смерджить логику перебора ways в один цикл?

2020-04-14 14:03 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
ну это так, чтобы знать, логику менять не надо

2020-04-14 14:05 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +				auto way = relation->Ways[element.first];
Хорошо

2020-04-14 14:41 UTC, Xanadar89 approved these changes

2020-04-14 14:41 UTC, merged