Documentation buildings
interactivevislab/GeoTempPlugins pull request #28
Opened 2020-04-14 18:29 UTC by kir1251

2020-04-16 15:49 UTC, Xanadar89 requested changes

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/Basics.h
> +/** routine to call libigl::tiangle with our data
libigl::tiangle очипятка, плюс функция не совсем такая

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/Basics.h
> + * @param inInner				list of inner contours aka holes
aka с точками писать надо

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/Basics.h
> +/** routine to call libigl::tiangle with our data
опять tiangle

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/BuildingsData.h
> +	/** Id */
ну не надо так

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/MasksLoader.h
> + * This class creating raster from input polygons and writes them to render target. The polygons are prepared by PolygonPreparer or its overrides.
Здесь и далее после \brief надо делать пустую строку с *

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/BlurShaderDeclaration.h
> +	//!@}
Надо изменить, такой способ оказывается не работает
Код стайл уже изменен

2020-04-16 15:49 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/PolygonMasksGenerator.h
>  	/** IModuleInterface implementation */
группировать надо

2020-04-21 10:13 UTC, kir1251 commented on GeoTempCore/Source/GeoTempCore/Public/Basics.h
> +/** routine to call libigl::tiangle with our data
Очипятка да, а через двоеточие я имел в виду название модуля библиотеки. Возможно, лучше как-то по другому написать, но не знаю, как.

2020-04-21 14:06 UTC, Xanadar89 requested changes

2020-04-21 14:06 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/Basics.h
> +	/** Earth radius */
В чём? в километрах, метрах, сантиметрах?

2020-04-21 14:06 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/GeometryData.h
> +	/** List of contours */
То что это список контуров и так видно, не надо писать очевидные вещи, пиши где и для чего они могут использоваться, например

2020-04-21 14:06 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Public/GeometryData.h
> +	 */
Здесь и далее отсутствует описание возвращаемых значений
Между функцией и комментарием к следующей функции надо оставлять хотя бы одну пустую строку

2020-04-23 10:39 UTC, Xanadar89 approved these changes

2020-04-23 13:43 UTC, merged