Foliage osm data fixing
interactivevislab/GeoTempPlugins pull request #29
Opened 2020-04-15 16:17 UTC by fyodorovvictor

Fixing unclosed relation contours and converting road lines into contours to remove them from foliage mask

2020-04-16 16:50 UTC, Xanadar89 requested changes

2020-04-16 16:50 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Private/Contour.cpp
> +	return (Points.Last() - Points[0]).Size2D() <= 1;
а не слишком ли большой эпсилон, аж 1?

2020-04-16 16:50 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +inline const double signedArea(const TArray<FVector> &p)
Почему имя функции с маленькой буквы?

2020-04-16 16:50 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +inline const TArray<FVector> border(const TArray<FVector> &p, double thickness)
и тут?
и inline убирай везде в cpp файлах

2020-04-17 10:05 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +inline const double signedArea(const TArray<FVector> &p)
Убрал функцию за ненадобностью

2020-04-17 10:05 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
> +inline const TArray<FVector> border(const TArray<FVector> &p, double thickness)
Также убрал функцию за ненадобностью

2020-04-17 10:06 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempCore/Private/Contour.cpp
> +	return (Points.Last() - Points[0]).Size2D() <= 1;
Нужно уточнить у Кирилла, так как он писал эту логику. Я ее лишь обернул.

2020-04-21 13:39 UTC, Xanadar89 requested changes

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/LoaderHelper.cpp
> +		}
если это обязательно надо выполнить на первом проходе, то что мешает вынести это за цикл, выше
if(inUnclosedContours.Num() > 0) 
{
    closedContours.Add(inUnclosedContours[0]);
	inUnclosedContours.RemoveAt(0);
}
while (inUnclosedContours.Num() > 0)
{
    ...
}
а так у тебя лишняя проверка которая выполняется на каждом цикле

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderBuildingsOsm.cpp
>  					}
у element.Value могут быть другие значения кроме inner outer?
Потому что если их только эти два, то этот код можно очень хорошо переписать

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderBuildingsOsm.cpp
>  					}
и тут тоже

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
>  	}
это что копия кода Влада? так делать нельзя, просто вызови уже существующую функцию

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
>  				if (element.Value == "outer")
а это копия кода Кирилла?

2020-04-21 13:39 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Public/CustomFoliageInstancer.h
> +														* < Place meshes from multiple FoliageMeshes as one layer.
зачем на 25 строчке начинать писать текст, если можно на 24
и далее также

2020-04-21 16:33 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
>  	}
У Влада этот код является частью функции создания меша дороги и не вынесен в отдельную функцию. Даже если я попробую вызывать функцию строительсва меша, то итоговые точки будут не в том порядке, который требуется для создания полигонов.

2020-04-21 16:37 UTC, fyodorovvictor commented on GeoTempCore/Source/GeoTempLoaders/Private/OSM/LoaderFoliageOsm.cpp
>  				if (element.Value == "outer")
Я брал за основу код Кирилла, так как в нем была логика чтения полигонов. Если я правильно понимаю, то код отличается тегами и способом их обработки, но сборка полигонов из точек одна и та же.

2020-04-23 15:58 UTC, Xanadar89 approved these changes

2020-04-23 15:58 UTC, merged