Tinyxml duplicate remove
interactivevislab/GeoTempPlugins pull request #30
Opened 2020-04-16 09:52 UTC by kir1251

2020-04-24 13:44 UTC, Xanadar89 requested changes

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempCore/Private/Contour.cpp
>  FContour::FContour(TArray<FVector> initPoints)
передавать надо по ссылке и внутри надо копировать не по одному вектору, который еще и лишний раз копируется, а просто добавить TArray к другому, у него есть для этого специальная функция

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/GeoTempPostgis/Public/PostgisReader.h
> +	static FMultipolygonData CreateContourFromBinary(FWkbEntity inEntity, FGeoCoords inGeoCoords);
FWkbEntity inEntity надо по ссылке передавать

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Private/BasePolygonPreparer.cpp
> +void UBasePolygonPreparer::PrepareMaskLoader(UMaskLoader* inTarget, TArray<FMultipolygonData> inPolygonData,
и тут TArray не по ссылке передается

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Private/TreeTypesPolygonPreparer.cpp
> +void UTreeTypesPolygonPreparer::PrepareMaskLoader(UMaskLoader* inTarget, TArray<FMultipolygonData> inPolygonData,
тут тоже

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Private/ZonesPolygonPreparer.cpp
> +void UZonesPolygonPreparer::PrepareMaskLoader(UMaskLoader* inTarget, TArray<FMultipolygonData> inPolygonData,
и тут

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/BasePolygonPreparer.h
> +	virtual void PrepareMaskLoader(UMaskLoader* inTarget, TArray<FMultipolygonData> inPolygonData,
и тут

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/TreeTypesPolygonPreparer.h
> +	void PrepareMaskLoader(UMaskLoader* inTarget, TArray<FMultipolygonData> inPolygonData,
не по стилю

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempCore/Source/PolygonMasksGenerator/Public/ZonesPolygonPreparer.h
> +	/** Overload of UBasePolygonPreparer */
и тут

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +                                                 UMaterialInterface* inWallMaterial, UMaterialInterface* inRoofMaterial, FString inTriangulationFlags)
возможно строки тоже стоит передавать по ссылке

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Private/BuildingUtils.cpp
> +void MeshHelpers::ConstructRuntimeMesh(URuntimeMeshComponent* runtimeMesh, FBuildingMeshData inMeshData, int inFirstSectionIndex)
даешь передачу всего по ссылкам

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/RoofMakers/ModernFlatRoof.h
> +	virtual FBuildingMeshData GenerateRoof_Implementation(const FBuildingPart& inBuildingPart, UMaterialInterface* inWallMaterial, UMaterialInterface* inRoofMaterial) override;
не по стилю

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempBuildings/Public/RoofMakers/SkeletonSlopeRoof.h
> +	/** Implementation of IRoofMaker */
и тут тоже

2020-04-24 13:44 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempTiles/Public/TileLoader.h
> +	/** Implementation of UActorComponent default functions */
и тут

2020-04-27 13:43 UTC, kir1251 commented on GeoTempVis/Source/GeoTempTiles/Public/TileLoader.h
> +	/** Implementation of UActorComponent default functions */
Не буду пока трогать, так как тайлы всё равно заново документировать

2020-04-27 14:05 UTC, Xanadar89 approved these changes

2020-04-27 14:06 UTC, merged