Polygon tree spawning
interactivevislab/GeoTempPlugins pull request #33
Opened 2020-04-28 13:11 UTC by fyodorovvictor

2020-05-21 21:31 UTC, Xanadar89 requested changes

2020-05-21 21:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +bool IsPointInPolygon(TArray<FVector> simPoly, FVector point)
TArray передается не по ссылке
И у меня такое чувство что эта функция должна быть где то еще

2020-05-21 21:31 UTC, Xanadar89 commented on GeoTempVis/Source/GeoTempFoliage/Public/CustomFoliageInstancer.h
> +			TArray<FContour> inExcludeHoles,
тоже не по ссылке

2020-05-22 10:22 UTC, fyodorovvictor commented on GeoTempVis/Source/GeoTempFoliage/Public/CustomFoliageInstancer.h
> +			TArray<FContour> inExcludeHoles,
Исправлено

2020-05-22 10:22 UTC, fyodorovvictor commented on GeoTempVis/Source/GeoTempFoliage/Private/CustomFoliageInstancer.cpp
> +bool IsPointInPolygon(TArray<FVector> simPoly, FVector point)
Эта функция была перенесена в GeometryData.h и GeometryData.cpp при работе в ветке polygonVisualizationFix и исправлена передача по ссылке.

2020-05-22 14:27 UTC, merged